### ISSUE TITLE
please don't pin numpy versions

### ISSUE THREAD

**Issue by agramfort** [CEA-COSMIC/ModOpt#169]
just sharing my experience now...

I just tried to install modopt on my conda env. As you pin requirements and you don't provide conda packages
I had to use pip. Doing so just downgraded numpy on my env and simply broke all my installation.

please please avoid pinning numpy versions (use >= and not ==) and consider pypi and conda packages

🙏

**Comment by sfarrens** [comment]
Hi @agramfort this is something we will be fixing soon. Sorry for the inconvenience.

**Comment by mathurinm** [comment]
:+1: pinning makes installation harder than it should be 

let me know if I can help !

**Comment by sfarrens** [comment]
Hi @mathurinm thanks for your interest. There is actual a good reason for why we did this as a temporary solution, but we will be removing the pinned versions for the next release, which is currently planned for mid December.

**Comment by agramfort** [comment]
could you do it ASAP on master branch and we install master in benchopt?
we don't need to wait for a release in benchopt

>

**Comment by sfarrens** [comment]
Hi @agramfort, absolutely. Apologies for the delay, I didn't realise you didn't need the formal release. I will do it this week and ping you.

**Comment by agramfort** [comment]
thanks !

>

**Comment by sfarrens** [comment]
@agramfort I have unpinned the package dependencies (at least those needed by users) in #189. This is currently available in the [develop](https://github.com/CEA-COSMIC/ModOpt/tree/develop) branch. Let me know if specifically need these changes in the master branch, if so I will merge this straight away. Otherwise, this will be merged for the next release (on or before 17/12/21).

**Comment by sfarrens** [comment]
Resolved in #189
